{{- $ingress := .Values.keycloak.ingress.internal -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}-internal
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
    {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range $ingress.paths }}
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ include "keycloak.fullname" $ }}-http
              {{- if $ingress.enableHttps }}
              servicePort: https
              {{- else }}
              servicePort: http
              {{- end }}
        {{- end }}
  {{- end }}
{{- end -}}
